version: '3.9'

services:
  web:
    container_name: app
    build: .
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    depends_on:
      - db
    command: bash -c "./wait-for-it.sh && npm start"
    networks:
      - nwads

  db:
    container_name: app-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: simpleERP
    networks:
      - nwads
    volumes:
      - ./data:/data:postgres
    ports:
      - "5432:5432"
networks:
  nwads:
    driver: bridge

volumes:
  data: