version: '3.9'

services:
  web:
    container_name: app
    build: .
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
      #- /home/node/app/node_modules #volume anonymous 

    depends_on:
      - db
    command: bash -c "./wait-for-it.sh"
    networks:
      - nwads
  db:
    container_name: app-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: simpleERP
    networks:
      - nwads
    volumes:
      - ./../db/vendasApinode/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  #tests:
  #  container_name: app-tests
  #  build: .
  #  volumes:
  #    - .:/usr/app
  #  command: npm run test:watch
networks:
  nwads:
    driver: bridge
volumes:
  data: